/** DSH 侧「代码图」skill 文案。落盘 <DSH_HOME>/skills/dsh-code-graph.md，watcher 自动发现。 */
export const SKILL_MARKDOWN = [
    '---',
    'name: dsh-code-graph',
    'description: |',
    '  代码图索引与结构化代码分析（DSH 原生版）。当用户输入“代码图”、“代码图 + 仓库”、“「代码图」+ xxx 仓库”、“代码图 xxx”或要求更新代码图/代码索引时触发。只说“代码图”时默认处理当前工作目录仓库。必须真实检查、更新并验证索引，不能只报告配置存在。',
    '---',
    '',
    '# 代码图（codegraph 原生工具）',
    '',
    '## 引擎',
    '',
    '- 唯一入口是 DSH 原生工具 \`codegraph\`（单工具分发器，后端为 codebase-memory 持久化代码图，非 MCP）。',
    '- 操作：\`projects\`（列项目）、\`status\`（索引状态）、\`index\`（建/增量索引）、\`query\`（BM25 符号/全文检索）、\`callers\`/\`callees\`（直接调用关系）、\`impact\`（向上影响面 BFS）、\`trace\`（调用/数据流路径）、\`architecture\`（架构概览）、\`snippet\`（按 qualified_name 取代码）、\`changes\`（变更检测）。',
    '- 查询族操作（query/callers/callees/impact/trace）自动做保鲜门控：head_sha/脏树漂移时先增量重索引再回答。',
    '',
    '## 分支管理',
    '',
    '- 索引按分支组织：分支项目名 = \`路径@分支\`。**切分支后无需手动重索引**——下次查询自动解析当前检出分支：已有该分支索引则直接复用（零重索引），没有则自动建（fast）。',
    '- \`branch\` 参数：查询族操作可显式指定分支（仅限已建索引的分支，查非检出分支时不做保鲜——索引是冻结态）；未建索引的分支 fail-loud 并列出可用分支。',
    '- 大仓单槽模式（DB 超过 \`branchIndexMaxDbBytes\`，默认 500MB）：每仓只保留当前分支一份索引，切分支即删旧建新（fast 全量重建，可能分钟级）；branch 参数仅预期分支可用。',
    '- \`op=status\` 查看当前分支、模式（multi/single）与可用分支清单；\`op=index\` 只能索引当前检出分支。',
    '- 非 git 目录 / \`branchIndex=false\` 时回退单索引跟随行为（项目名为纯路径派生）。',
    '',
    '## 使用流程',
    '',
    '1. 从用户输入解析仓库路径；未明确时用当前工作目录。目标必须是 Git 仓库（用 \`git -C <repo> rev-parse --show-toplevel\` 验证），失败就报告，不要把任意目录当仓库。',
    '2. 先 \`op=status\`（带 repo_path 或 project）；项目不存在/未索引时先 \`op=index, repo_path=<repo>\`（默认 fast 模式，增量）。切分支后直接查询即可，分支索引自动跟随。',
    '3. 结构化读代码优先级：跨文件理解一律先 \`query\`/\`callers\`/\`callees\`/\`impact\`/\`trace\`，命中后用 \`snippet\` 取代码确认；图零命中会自动回落 ripgrep（结果带 fallback 标注），不要自己再瞎 grep 一轮。',
    '4. 汇报必须带真实证据：project 名、branch、status、nodes/edges、查询命中行；索引动作未返回成功证据前不得说“已更新”。',
    '',
    '## 并发与安全纪律（强制）',
    '',
    '- **只有主 agent 可以执行 \`op=index\`**。sub-agent / reviewer 只允许查询操作（projects/status/query/callers/callees/impact/trace/architecture/snippet/changes）；即使继承的用户提示包含“代码图”，也要把索引请求交回主 agent。',
    '- 主 agent 派发 sub-agent 前先完成索引检查/更新，并在 sub-agent prompt 中写明“只查询，禁止重建索引”。',
    '- 对同一仓库，引擎侧单飞保护已内置：不要并行重复发起 index。',
    '- 本插件不改用户仓库文件、不写 .gitignore、不启动常驻监听；引擎缺失时明确报错，不要静默降级。',
].join('\n');
//# sourceMappingURL=skill.js.map